#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_LOADDATA)        += loaddata

# list of libraries the app needs to build
loaddata-y                          = common libsel4 libmuslc libsel4vka libcpio libelf \
                                      libsel4allocman \
                                      libsel4platsupport libsel4platsupport libsel4muslcsys libsel4test \
                                      libsel4simple libsel4vspace libsel4utils libutils

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
loaddata-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
loaddata-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# add the tests app  as a component so that we can elf load it
loaddata-components-y += sel4test-tests
loaddata-components = $(addprefix $(STAGE_BASE)/bin/, $(loaddata-components-y))

loaddata: export COMPONENTS=${loaddata-components}
loaddata: ${loaddata-components-y} kernel_elf $(loaddata-y)
