#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

apps-$(CONFIG_APP_LOADDATA2)        += loaddata2

# list of libraries the app needs to build
loaddata2-y                          = common libsel4 libmuslc libsel4vka libcpio libelf \
                                      libsel4allocman \
                                      libsel4platsupport libsel4platsupport libsel4muslcsys libsel4test \
                                      libsel4simple libsel4vspace libsel4utils libutils

# set up correct simple lib for our kernel
ifdef CONFIG_KERNEL_STABLE
loaddata2-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
loaddata2-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# add the tests app  as a component so that we can elf load it
#loaddata2-components-y += sel4test-tests
#loaddata2-components = $(addprefix $(STAGE_BASE)/bin/, $(loaddata2-components-y))

#loaddata2: export COMPONENTS=${loaddata2-components}
#loaddata2: ${loaddata2-components-y} kernel_elf $(loaddata2-y)
loaddata2: kernel_elf $(loaddata2-y)
