#
# Copyright (c) 2015, Josef Mihalits
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
#

apps-$(CONFIG_APP_MULTIIRQS) += multiirqs

# dependencies
multiirqs-y = common libsel4 libmuslc libsel4muslcsys libsel4vka \
              libsel4allocman libsel4simple \
              libsel4platsupport libsel4vspace libsel4utils libutils

ifdef CONFIG_KERNEL_STABLE
multiirqs-$(CONFIG_LIB_SEL4_SIMPLE_STABLE) += libsel4simple-stable
else
multiirqs-$(CONFIG_LIB_SEL4_SIMPLE_DEFAULT) += libsel4simple-default
endif

# dependencies
multiirqs: kernel_elf $(multiirqs-y)
